"""
Location: pact-plugin/tests/test_lint_check_argument_accounting.py
Summary: One invariant of lint-check.sh --files: every argument a caller can
         pass is ACCOUNTED FOR by the dispatch loop, incrementing exactly one
         of its three counters. The `SKIPPED (no arguments given)` verdict is
         true only because of this property.
Used by: pytest suite.

WHY THIS IS ITS OWN MODULE, not another arm beside the verdict tests in
test_lint_check_files_mode.py:

    That module pins WHICH string each reachable state produces. This one pins
    that no state can reach the WRONG BRANCH at all. It is an invariant about
    the dispatch loop rather than about any one verdict, so it outlives every
    string currently emitted -- rename all four verdicts and this file still
    states something true and still fails when the loop stops accounting for
    an argument. Sitting it beside the string pins would invite a later editor
    to treat it as one more string pin and move it along with them, which is
    the coupling it exists to prevent.

THE INVARIANT, and why it is asserted in this form:

    The loop keeps three counters -- PY_FILES, UNRESOLVED, IGNORED -- and the
    verdict at the empty-PY_FILES branch reads "no arguments given", which is
    true ONLY IF an argument that reaches the loop always increments one of
    them. The `*)` arm is what makes that hold for everything a caller can
    pass, including the empty string.

    Those counters are internal to a script that exits, so nothing outside can
    read them. What IS observable is the contrapositive, at exactly the point
    where a broken invariant becomes a lie a caller can read:

        argc >= 1  =>  the verdict is NEVER "no arguments given"

    An argument incrementing no counter, passed alone, leaves PY_FILES empty
    with both other counters at zero -- landing in that branch and telling a
    caller who passed an argument that they passed none. So this is not a
    proxy for the counter equation; it is the equation's failure mode at the
    only boundary where it does harm.

INPUTS ARE GENERATED BY A RULE, NOT LISTED:

    A hand-written list of argument shapes would be a floor -- green by
    construction, thorough-looking, and silent about the first shape nobody
    thought of. The cases below are a CROSS-PRODUCT over independent
    dimensions (suffix x filesystem kind) plus the degenerate strings that sit
    outside that product. Extending coverage means adding a value to one
    dimension, which re-crosses with every other; it does not mean appending a
    case. That is the difference that stops a set of inputs being a floor.

    Not used: a property-based generator. `hypothesis` is named in the CI
    dependency set but its arms SKIP where it is absent, and a guard that
    skips in the environment the suite actually runs in is not a guard.
"""

import subprocess
from pathlib import Path

_SCRIPT = (
    Path(__file__).parent.parent
    / "skills"
    / "pact-coding-standards"
    / "scripts"
    / "lint-check.sh"
)

_NO_ARGS = "IMPORT-HYGIENE: SKIPPED (no arguments given)"

# Dimension 1: how the argument ends. `.py` is the only suffix the filter
# matches, and the match is case-sensitive, so `.PY` must fall to `*)`.
_SUFFIXES = ["", ".py", ".txt", ".PY", ".py.bak"]

# Dimension 2: what the path resolves to. Only a regular file survives to be
# checked; a directory and an absent path each take a different reporting arm.
_KINDS = ["absent", "file", "dir"]


def _materialise(tmp_path, index, suffix, kind):
    """Build one argument from a (suffix, kind) pair in the product.

    The stem is index-derived rather than suffix-derived on purpose: `.py` and
    `.PY` differ to the script's case-sensitive `*.py` filter but name the SAME
    path on a case-insensitive filesystem (the macOS default), so a
    suffix-derived stem collides between those two rows of the product.
    """
    target = tmp_path / f"arg{index}{suffix}"
    if kind == "file":
        target.write_text("import os\nprint(os.sep)\n", encoding="utf-8")
    elif kind == "dir":
        target.mkdir()
    return str(target)


def _generated_arguments(tmp_path):
    """The cross-product, plus degenerate strings that lie outside it.

    Yields (label, argv_entry). The label names the class so a failure says
    which one the loop stopped accounting for.
    """
    index = 0
    for suffix in _SUFFIXES:
        for kind in _KINDS:
            index += 1
            yield f"suffix={suffix or '(none)'} kind={kind}", _materialise(
                tmp_path, index, suffix, kind
            )

    # Shapes with no filesystem identity, so they cannot come from the product
    # above. Each is a real thing a caller has produced or can produce.
    yield "empty string", ""
    yield "whitespace only", "   "
    yield "unsplit quoted list", f"{tmp_path}/a.py {tmp_path}/b.py"
    yield "leading dash", "-notaflag.py"
    yield "non-ascii", str(tmp_path / "éà中.py")
    yield "bare name, no directory", "relative.py"


def _verdict(*argv):
    proc = subprocess.run(
        ["bash", str(_SCRIPT), "--files", *argv],
        capture_output=True,
        text=True,
    )
    lines = [line for line in proc.stdout.splitlines() if line]
    return (lines[-1] if lines else ""), proc


def test_every_argument_class_is_accounted_for(tmp_path):
    """No argument, alone, may reach the no-arguments verdict.

    Deleting the `*)` arm from the dispatch loop drops every non-.py class
    without incrementing a counter, which lands those arguments in the
    empty-PY_FILES branch -- and this fails, naming each dropped class.
    """
    unaccounted = []
    for label, arg in _generated_arguments(tmp_path):
        verdict, proc = _verdict(arg)
        if verdict == _NO_ARGS:
            unaccounted.append(f"  {label}: {arg!r} -> {verdict}")
        # Whatever else it did, it must not have crashed the fail-open contract.
        assert proc.returncode in (0, 1), (
            f"{label}: {arg!r} exited {proc.returncode}; the --files tier must "
            f"exit 0 (pass or degraded) or 1 (findings), never anything else"
        )

    assert not unaccounted, (
        "the dispatch loop stopped accounting for "
        f"{len(unaccounted)} argument class(es). Each was passed as the ONLY "
        "argument and still produced the verdict claiming nothing was given, "
        "which is the lie the counter-exhaustiveness property prevents:\n"
        + "\n".join(unaccounted)
    )
